In [4]:
import torch
import torch.nn.functional as F
import math

def scaled_dot_product_attention(Q, K, V):
    """
    Q: (batch, heads, seq_len_q, d_k)
    K: (batch, heads, seq_len_k, d_k)
    V: (batch, heads, seq_len_k, d_v)
    """
    d_k = Q.size(-1)

    # raw scores
    scores = torch.matmul(Q, K.transpose(-2, -1))  # (batch, heads, seq_len_q, seq_len_k)
    print("Raw scores (before scaling):")
    print(scores)

    # scaled scores
    scores_scaled = scores / math.sqrt(d_k)
    print("\nScaled scores (after dividing by sqrt(d_k)):")
    print(scores_scaled)

    # softmax over keys
    attn_weights = F.softmax(scores_scaled, dim=-1)
    print("\nAttention weights (after softmax):")
    print(attn_weights)

    # output
    output = torch.matmul(attn_weights, V)
    print("\nOutput vectors (Attention(Q,K,V)):")
    print(output)

    return output, attn_weights


if __name__ == "__main__":
    torch.manual_seed(0)

    batch_size = 1
    num_heads = 1
    seq_len_q = 3
    seq_len_k = 3
    d_k = 4
    d_v = 4

    Q = torch.randn(batch_size, num_heads, seq_len_q, d_k)
    K = torch.randn(batch_size, num_heads, seq_len_k, d_k)
    V = torch.randn(batch_size, num_heads, seq_len_k, d_v)

    print("Q:\n", Q)
    print("\nK:\n", K)
    print("\nV:\n", V)

    output, attn_weights = scaled_dot_product_attention(Q, K, V)


Q:
 tensor([[[[ 1.5410, -0.2934, -2.1788,  0.5684],
          [-1.0845, -1.3986,  0.4033,  0.8380],
          [-0.7193, -0.4033, -0.5966,  0.1820]]]])

K:
 tensor([[[[-0.8567,  1.1006, -1.0712,  0.1227],
          [-0.5663,  0.3731, -0.8920, -1.5091],
          [ 0.3704,  1.4565,  0.9398,  0.7748]]]])

V:
 tensor([[[[ 0.1919,  1.2638, -1.2904, -0.7911],
          [-0.0209, -0.7185,  0.5186, -1.3125],
          [ 0.1920,  0.5428, -2.2188,  0.2590]]]])
Raw scores (before scaling):
tensor([[[[ 0.7606,  0.1035, -1.4638],
          [-0.9395, -1.5321, -1.4103],
          [ 0.8337,  0.5143, -1.2736]]]])

Scaled scores (after dividing by sqrt(d_k)):
tensor([[[[ 0.3803,  0.0517, -0.7319],
          [-0.4697, -0.7661, -0.7052],
          [ 0.4168,  0.2572, -0.6368]]]])

Attention weights (after softmax):
tensor([[[[0.4881, 0.3514, 0.1605],
          [0.3947, 0.2935, 0.3119],
          [0.4543, 0.3873, 0.1584]]]])

Output vectors (Attention(Q,K,V)):
tensor([[[[ 0.1171,  0.4515, -0.8037, -0.8058],